// infra-message-client :: EventPublisher port implementation + Kafka messaging.

apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':infra-common')
    implementation 'org.springframework.kafka:spring-kafka'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

bootJar.enabled = false
jar.enabled = true
