// infra-http-client :: HTTP client infrastructure.
// Implements HttpClient port from core-entities via OkHttp.

apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':infra-common')
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}

bootJar.enabled = false
jar.enabled = true
