spring:
  datasource:
    url: ${env_datasource_url}
    username: ${env_datasource_username}
    password: ${env_datasource_password}
    driver-class-name: org.postgresql.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.isClustered: true
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.threadCount: 4
