spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/payhub}
    username: ${DATASOURCE_USERNAME:payhub}
    password: ${DATASOURCE_PASSWORD:payhub123}
    driver-class-name: org.postgresql.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.isClustered: true
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.threadCount: 4
