management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,conditions
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
